# Database settings.
database:

  # the name of your JDBC driver
  #driverClass: org.h2.Driver
  driverClass: org.postgresql.Driver

  # the username
  #user: sa
  user: ${env.DB_USER!'postgres'}

  # the password
  #password: sa
  password: ${env.DB_PASSWORD!''}

  # the JDBC URL
  #url: jdbc:h2:current
  #url: jdbc:postgresql://127.0.0.1:5432/current
  url: jdbc:postgresql://${env.DB_HOST!'localhost'}:${env.DB_PORT!'32768'}/${env.DB_NAME!'current'}

server:
  applicationConnectors:
    - type: 'http'
      port: '8080'

  adminConnectors:
    - type: 'http'
      port: '8081'

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.whatplayed: DEBUG

  appenders:
    - type: console

swagger:
  enabled: true
  resourcePackage: com.whatplayed.resources
  schemes:
    - http
  swaggerViewConfiguration:
    showAuth: false
    pageTitle: WhatPlayed
