# Database settings.
database:

  # the name of your JDBC driver
  #driverClass: org.h2.Driver
  driverClass: org.postgresql.Driver

  # the username
  #user: sa
  user: postgres

  # the password
  #password: sa
  password:

  # the JDBC URL
  #url: jdbc:h2:current
  #url: jdbc:postgresql://127.0.0.1:5432/current
  url: jdbc:postgresql://localhost:32768/current

server:
  applicationConnectors:
    - type: 'http'
      port: '8080'

  adminConnectors:
    - type: 'http'
      port: '8081'

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    net.krisr.current: DEBUG

  appenders:
    - type: console

swagger:
  enabled: true
  resourcePackage: net.krisr.current.resources
  schemes:
    - http
  swaggerViewConfiguration:
    showAuth: false
    pageTitle: Current Play Tracker